name: build and release

on:
  release:
    types: [published]  # Trigger on release published event

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup docker
        run: docker pull registry.access.redhat.com/ubi8/ubi:8.1
      
      - name: run docker
        run: |
            docker run --rm -v $PWD:/workspace -w /workspace registry.access.redhat.com/ubi8/ubi:latest bash -c " 
            yum install -y epel-release
            yum groupinstall -y 'Development Tools'
            yum install -y krb5-devel compat-openssl11 python3-pip python3-venv python3-wheel git cmake gcc gcc-c++ openssl-devel
            git submodule update --init --recursive
            make
            pip install src/python/dist/adbc_driver_netezza*.whl
            pip install pyarrow
            python3 -c 'from adbc_driver_netezza import StatementOptions, dbapi
            uri = \"netezza://admin:password@am9001.fyre.ibm.com:5480/system\"
            with dbapi.connect(uri) as conn:
              print(conn)'
            "
