name: build and release

on:
  release:
    types: [published]  # Trigger on release published event

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo yum install openssl-devel krb5-devel compat-openssl11 -y

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build and publish release
        run: |
          make
          gh release upload ${{ github.event.release.tag_name }} WithMakeBuild/adbc_driver_netezza.tgz
          pip install twine
          echo "Uploading distributions to PyPI..."
          twine upload src/python/dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}