name: build and release
on: release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: prerequisite
      run: sudo apt-get install -y libkrb5-dev
    - name: submodule
      run: git submodule update --init --recursive
    - name: make
      run: make
    - name: release
      run: |
        set THIS_GITHUB_EVENT=$(cat $GITHUB_EVENT_PATH)
        set RELEASE_UPLOAD_URL=$(echo $THIS_GITHUB_EVENT | jq -r .release.upload_url)
        set RELEASE_UPLOAD_URL=${RELEASE_UPLOAD_URL/\{?name,label\}/}
        set RELEASE_TAG_NAME=$(echo $THIS_GITHUB_EVENT | jq -r .release.tag_name)
        set PROJECT_NAME=$(basename $GITHUB_REPOSITORY)
        NAME="adbc_driver_netezza.tgz"
        curl \
          --tlsv1.2 \
          -X POST \
          --data-binary WithMakeBuild/adbc_driver_netezza.tgz \
          -H 'Content-Type: application/octet-stream' \
          -H "Authorization: Bearer ${GITHUB_TOKEN}" \
          "${RELEASE_UPLOAD_URL}?name=${NAME}"

    
