name: build and release

on:
  release:
    types: [published]  # Trigger when a release is published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: sudo apt-get install -y libkrb5-dev
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Build and publish release
        run: |
          make
          gh release upload ${{ github.event.release.tag_name }} WithMakeBuild/adbc_driver_netezza.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-to-pypi:
    name: Publish Python distribution to PyPI
    needs: build  # Ensure this runs after the build job is finished
    runs-on: ubuntu-latest

    environment:
      name: nz-adbc-release

    permissions:
      id-token: write  # Mandatory for trusted publishing

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Specify the Python version (e.g., 3.8, 3.9)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine  # Install twine for uploading to PyPI

      - name: Verify distribution files location
        run: |
          echo "Checking the contents of src/python/dist/"
          ls -l src/python/dist  # List the contents of the directory

      - name: Upload Python distributions to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}  # Fetch PyPI username from secrets
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # Fetch PyPI password or API token from secrets
        run: |
          echo "Uploading distributions to PyPI..."
          twine upload src/python/dist/*  # Upload the pre-built package from the dist directory
