name: build and release

on:
  release:
    types: [published]  # Trigger on release published event

jobs:
  build:
    runs-on: ubuntu-20.04  # Use Ubuntu 20.04 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use v4 of actions/checkout

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Set Python version to 3.9

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openssl libkrb5-dev python3-pip python3-venv python3-wheel

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build the package
        run: |
          make

      - name: Install the Python package from the .whl file
        run: |
          pip install src/python/dist/adbc_driver_netezza*.whl
          pip install pyarrow

      - name: Run the test
        run: |
          python3 -c 'from adbc_driver_netezza import StatementOptions, dbapi
          uri = "netezza://admin:password@am9001.fyre.ibm.com:5480/system"
          with dbapi.connect(uri) as conn:
              print(conn)'
