name: build and release

on:
  release:
    types: [published]  # Trigger on release published event

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build and publish release
        run: |
          make
          gh release upload ${{ github.event.release.tag_name }} WithMakeBuild/adbc_driver_netezza.tgz
          pip install twine  # Install twine to upload packages
          echo "Uploading distributions to PyPI..."
          twine upload src/python/dist/*  # Upload the distribution files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
